import basics.decisions.nested_decision.nestception as nestception
import basics.decisions.nested_decision.nested as nested
import basics.decisions.simple_decision.comparison_opertators as comparison_opertators
import basics.decisions.simple_decision.counter as counter
import basics.decisions.simple_decision.if_elif_else as if_elif_else
import basics.decisions.simple_decision.if_else as if_else
import basics.decisions.simple_decision.if_if as if_if
import basics.decisions.simple_decision.modulo_operator as modulo_operator
import basics.decisions.and_operator as and_operator
import basics.decisions.or_operator as or_operator
import basics.decisions.review as review
import basics.functions.ascii_character as ascii_character
import basics.functions.ascii_code as ascii_code
import basics.functions.function_calls as function_calls
import basics.functions.function_with_loop as function_with_loop
import basics.functions.function_with_nesting as function_with_nesting
import basics.functions.function_with_parameter as function_with_parameter
import basics.functions.function_with_parameters as function_with_parameters
import basics.functions.multiple_functions as multiple_functions
import basics.functions.return_values as return_values
import basics.functions.simple_function as simple_function
import basics.input.ascii_robot as ascii_robot
import basics.input.data_types as data_types
import basics.input.string_operators as string_operators
import basics.input.user_input as user_input
import basics.modules.guess_the_number as guess_the_number
import basics.output.ascii_art as ascii_art
import basics.output.escape_charaters as escape_charaters
import basics.output.simple_message as simple_message

eval(input("Please enter a function name\n"))