def run():
    print("System Failure Imminent!")
    print("System reboot has been initiated...")
    print("\n\n...rebooting sensory system")
    print("...rebooting output motors")
    print("...rebooting hover engine\n\nSytem online.")
    print("##########")
    print("#        #")
    print("#        #")
    print("##########")
    print("  #    #  ")
    print("#        #")
    print("  ##  ## ")
    print("What is your name human?")
    name = input()
    print("It is nice to meet you human", name)
    name = input("Name? ")
    age = int(input("Age in years? "))
    height = float(input("Height in metres? "))
    weight = float(input("Weight in Kg? "))
    print("Name: ", name)
    print("Age:", str(age))
    print("Height: ", str(round(height, 2)))
    print("Weight: ", str(round(weight, 2)))
    BMI = weight / (height ** 2)
    print("BMI: ", round(BMI, 2))
    print("eye char: ")
    eye = input()
    print("##########")
    print("#",eye,"  ",eye,"#")
    print("#  ----  #")
    print("##########")
    print("  #    #  ")
    print("#        #")
    print("  ##  ## ")
    lives = int(input("Number of Lives: "))
    energy = int(input("Energy Level: "))
    shield = int(input("Shield Level: "))
    print("Lives: ", lives*"♥")
    print("Energy: ", energy*"♦")
    print("Shield: ", shield*"♦")